### ISSUE TITLE
Current version is not suitable for the lastest stable version HBase 0.92.1 

### ISSUE THREAD

**Issue by juneng603** [mushkevych/surus#2]
in a HBase 0.92.1, there are some changes in interfaces to use HTablePool.

for example, 
- putTable() is deprecated. 
- getTable() returns a HTableInterface not a HTable.

**Comment by mushkevych** [comment]
Fixed by:
- implementing support for new Cloudera CDH 4.0.1 distribution folder structure for build.xml
- handling HTablePool IOException that is now thrown for putTable and closePool methods

As of now, I have not completely replaced the deprecated methods, as HTableInterface has no support for setting caching buffer, while both HTable and PooledHTable suit our use-case

**Comment by mushkevych** [comment]
Note: changes makes the code incompatible with CDH 3.x.x distros
